# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.labCod = QtWidgets.QLabel(self.centralwidget)
        self.labCod.setGeometry(QtCore.QRect(30, 20, 61, 21))
        self.labCod.setObjectName("labCod")

        self.labQuant = QtWidgets.QLabel(self.centralwidget)
        self.labQuant.setGeometry(QtCore.QRect(30, 50, 71, 21))
        self.labQuant.setObjectName("labQuant")

        self.btnAdicionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdicionar.setGeometry(QtCore.QRect(50, 90, 91, 31))
        self.btnAdicionar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAdicionar.setMouseTracking(False)
        self.btnAdicionar.setObjectName("btnAdicionar")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 160, 651, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.txtCod = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCod.setGeometry(QtCore.QRect(100, 20, 71, 20))
        self.txtCod.setObjectName("txtCod")

        self.txtQuant = QtWidgets.QLineEdit(self.centralwidget)
        self.txtQuant.setGeometry(QtCore.QRect(100, 50, 71, 20))
        self.txtQuant.setObjectName("txtQuant")

        self.commandLinkButton = QtWidgets.QCommandLinkButton(
            self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(500, 10, 131, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.tabCarrinho = QtWidgets.QTableWidget(self.centralwidget)
        self.tabCarrinho.setGeometry(QtCore.QRect(10, 180, 611, 261))
        self.tabCarrinho.setShowGrid(True)
        self.tabCarrinho.setObjectName("tabCarrinho")
        self.tabCarrinho.setColumnCount(0)
        self.tabCarrinho.setRowCount(0)

        self.btnRemover = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemover.setGeometry(QtCore.QRect(410, 130, 101, 31))
        self.btnRemover.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRemover.setMouseTracking(False)
        self.btnRemover.setObjectName("btnRemover")

        self.btnLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpar.setGeometry(QtCore.QRect(520, 130, 91, 31))
        self.btnLimpar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLimpar.setMouseTracking(False)
        self.btnLimpar.setObjectName("btnLimpar")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labCod.setText(_translate("MainWindow", "Código:"))
        self.labQuant.setText(_translate("MainWindow", "Quantidade:"))
        self.btnAdicionar.setText(_translate("MainWindow", "Adicionar"))
        self.commandLinkButton.setText(_translate("MainWindow", "Acessar ADM"))
        self.tabCarrinho.setSortingEnabled(False)
        self.btnRemover.setText(_translate("MainWindow", "Remover Produto"))
        self.btnLimpar.setText(_translate("MainWindow", "Limpar Carrinho"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
