# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(250, 200)
        LoginWindow.setMinimumSize(QtCore.QSize(250, 200))
        LoginWindow.setMaximumSize(QtCore.QSize(250, 200))
        self.labTitulo = QtWidgets.QLabel(LoginWindow)
        self.labTitulo.setGeometry(QtCore.QRect(70, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labTitulo.setFont(font)
        self.labTitulo.setObjectName("labTitulo")
        self.labSenha = QtWidgets.QLabel(LoginWindow)
        self.labSenha.setGeometry(QtCore.QRect(40, 90, 41, 16))
        self.labSenha.setObjectName("labSenha")
        self.labLogin = QtWidgets.QLabel(LoginWindow)
        self.labLogin.setGeometry(QtCore.QRect(40, 60, 61, 16))
        self.labLogin.setObjectName("labLogin")
        self.txtLoginLogin = QtWidgets.QLineEdit(LoginWindow)
        self.txtLoginLogin.setGeometry(QtCore.QRect(80, 60, 121, 20))
        self.txtLoginLogin.setObjectName("txtLoginLogin")
        self.txtLoginSenha = QtWidgets.QLineEdit(LoginWindow)
        self.txtLoginSenha.setGeometry(QtCore.QRect(80, 90, 121, 20))
        self.txtLoginSenha.setObjectName("txtLoginSenha")
        self.btnLogingLogin = QtWidgets.QPushButton(LoginWindow)
        self.btnLogingLogin.setGeometry(QtCore.QRect(120, 130, 81, 31))
        self.btnLogingLogin.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogingLogin.setMouseTracking(False)
        self.btnLogingLogin.setObjectName("btnLogingLogin")
        self.btnLoginCancelar = QtWidgets.QPushButton(LoginWindow)
        self.btnLoginCancelar.setGeometry(QtCore.QRect(40, 130, 71, 31))
        self.btnLoginCancelar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoginCancelar.setMouseTracking(False)
        self.btnLoginCancelar.setObjectName("btnLoginCancelar")
        self.txtLoginMessage = QtWidgets.QLineEdit(LoginWindow)
        self.txtLoginMessage.setEnabled(True)
        self.txtLoginMessage.setGeometry(QtCore.QRect(40, 170, 161, 20))
        self.txtLoginMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLoginMessage.setReadOnly(True)
        self.txtLoginMessage.setObjectName("txtLoginMessage")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.labTitulo.setText(_translate("LoginWindow", "FAZER LOGIN"))
        self.labSenha.setText(_translate("LoginWindow", "Senha:"))
        self.labLogin.setText(_translate("LoginWindow", "Login:"))
        self.btnLogingLogin.setText(_translate("LoginWindow", "Login"))
        self.btnLoginCancelar.setText(_translate("LoginWindow", "Cancelar"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QDialog()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
